name: Test Auth Service with Docker

on:
  push:
    paths:
      - "agrovera_microservices/auth_service/**"
  pull_request:
    paths:
      - "agrovera_microservices/auth_service/**"

jobs:
  test-auth:
    name: Build & Test auth_service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t auth-service-test ./agrovera_microservices/auth_service

      - name: Run tests in container
        run: |
          docker run auth-service-test test
